src/Entity/UserSync.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Exception\UserHasSyncInProgressException;
use App\Repository\UserSyncRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserSyncRepository::class)]
class UserSync
{
    #[ORM\Id]
    #[ORM\OneToOne(inversedBy: 'sync')]
    private User $user;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $token;

    #[ORM\Column(nullable: true)]
    private ?int $accountId;

    #[ORM\Column(nullable: true)]
    private ?UserSyncState $state;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $syncedAt;

    public function __construct(User $user)
    {
        $this->user = $user;
        $this->token = null;
        $this->accountId = null;
        $this->state = null;
        $this->syncedAt = null;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getAccountId(): ?int
    {
        return $this->accountId;
    }

    public function setAccountId(?int $accountId): self
    {
        $this->accountId = $accountId;

        return $this;
    }

    public function getState(): ?UserSyncState
    {
        return $this->state;
    }

    public function setState(?UserSyncState $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getSyncedAt(): ?DateTimeImmutable
    {
        return $this->syncedAt;
    }

    public function setSyncedAt(?DateTimeImmutable $syncedAt): self
    {
        $this->syncedAt = $syncedAt;

        return $this;
    }

    /**
     * @phpstan-assert-if-true !null $this->getAccountId()
     * @phpstan-assert-if-true !null $this->getToken()
     */
    public function isLinked(): bool
    {
        return null !== $this->accountId && null !== $this->token;
    }

    public function isInProgress(): bool
    {
        return null !== $this->state && UserSyncState::FAILED !== $this->state;
    }

    /**
     * @throws UserHasSyncInProgressException
     */
    public function ensureNoActiveSync(): void
    {
        if ($this->isInProgress()) {
            throw UserHasSyncInProgressException::create($this->getUser());
        }
    }
}

templates/components/AnimeList.html.twig
<section class="mt-4">
  <table class="anime-list table bg-base-200 rounded-box shadow-lg shadow-base-300 mt-4">
    <thead>
    <tr>
      <th>Name</th>
      <th class="hidden md:table-cell">Kind</th>
      <th class="hidden md:table-cell">Status</th>
      <th>Score</th>
    </tr>
    </thead>
    <tbody>
    <twig:AnimeListGroup title="Watching / Rewatching" items="{{ this.watchingOrRewatching }}" />
    <twig:AnimeListGroup title="On hold" items="{{ this.onHold }}" />
    <twig:AnimeListGroup title="Planned" items="{{ this.planned }}" />
    <twig:AnimeListGroup title="Completed" items="{{ this.completed }}" />
    <twig:AnimeListGroup title="Dropped / Skipped" items="{{ this.droppedOrSKipped }}" />
    </tbody>
  </table>
</section>

templates/components/AnimeListGroup.html.twig
<tr class="bg-base-300">
  <th colspan="4">
    <span>{{ title }}</span>
    <span class="badge badge-primary">{{ this.items|length }}</span>
  </th>
</tr>
{% for item in this.items %}
  <tr>
    <td>
      <p><a href="{{ item.animeUrl|shikimori_url }}" class="link">{{ item.animeName }}</a></p>
      <p class="md:hidden">{{ item.animeKind.value }} / {{ item.animeStatus.value }}</p>
    </td>
    <td class="hidden md:table-cell">{{ item.animeKind.value }}</td>
    <td class="hidden md:table-cell">{{ item.animeStatus.value }}</td>
    <td>{% if item.score > 0 %}{{ item.score }}{% else %}&mdash;{% endif %}</td>
  </tr>
{% endfor %}

templates/components/Flash.html.twig
<section {{ stimulus_action('flash', 'destroy', 'click') }}
  class="flash mt-4 p-4 rounded-box shadow-lg shadow-base-300 bg-error font-bold text-base-300"
>
  {% block content %}{% endblock %}
</section>

templates/components/NavBar.html.twig
<nav id="navbar" class="bg-base-300">
  <div class="navbar lg:container lg:mx-auto">
    <div class="navbar-start">
      <div class="dropdown">
        <label tabindex="0" class="btn btn-ghost lg:hidden">
          {% include 'icons/navbar_dropdown.svg.twig' %}
        </label>
        <ul tabindex="0" class="z-[1] menu dropdown-content bg-base-300 rounded-box shadow-lg shadow-base-300 mt-4">
          {% for item in this.items %}
            <li>
              <a href="{{ item.path }}" class="{{ html_classes({'active': item.active}) }}">
                {{ item.label }}
                {% if item.count is defined %}
                  <span class="badge badge-accent">{{ item.count }}</span>
                {% endif %}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
      <a href="{{ path('app_anime_index') }}" class="btn btn-ghost normal-case text-xl">Iromikihs</a>
    </div>

    <div class="navbar-center hidden lg:flex">
      <ul class="menu menu-horizontal">
        {% for item in this.items %}
          <li>
            <a href="{{ item.path }}" class="{{ html_classes({'active': item.active}) }}">
              {{ item.label }}
              {% if item.count is defined %}
                <span class="badge badge-accent">{{ item.count }}</span>
              {% endif %}
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>

    <div class="navbar-end" data-turbo="false"><a href="{{ path('app_logout') }}">Log out</a></div>
  </div>
</nav>

templates/components/PageHeader.html.twig
<section class="page-header mt-4">
  <h1 class="text-3xl font-bold">{% block content %}{% endblock %}</h1>
</section>

templates/components/SeriesList.anime_form.html.twig
{% if state is null %}
  {% set action = path('app_anime_skip', {anime: id}) %}
{% else %}
  {% set action = path('app_anime_observe', {anime: id}) %}
{% endif %}
<form id="anime-{{ id }}-skip-form" method="post" action="{{ action }}" class="inline">
  <input type="hidden" name="{{ csrfName }}" value="{{ csrfValue }}" />
  <button
    class="{{ html_classes('uppercase', 'font-bold', {
      'link': not syncInProgress,
      'link-error': not syncInProgress and state is null,
      'link-success': not syncInProgress and state is not null,
    }) }}"
    {% if syncInProgress %}disabled{% endif %}
  >
    {% if state is null %}Skip{% else %}Observe{% endif %}
  </button>
</form>

templates/components/SeriesList.html.twig
{% set csrfName = constant('App\\Controller\\Controller::COMMON_CSRF_TOKEN_FIELD') %}
{% set csrfValue = csrf_token(constant('App\\Controller\\Controller::COMMON_CSRF_TOKEN_ID')) %}

{% set syncInProgress = this.user.sync.inProgress %}

<section class="series-list columns-1 xl:columns-2 mt-4">
  {% for series in this.series %}
    <div
      id="series-{{ series.id }}"
      class="series-list-item bg-base-200 rounded-box shadow-lg shadow-base-300 mb-5 p-5 break-inside-avoid"
    >
      <h2 class="text-2xl font-bold">{{ series.name }}</h2>

      {% if series.state.value != 'dropped' %}
        {% set action = path('app_series_drop', {seriesRate: series.seriesRateId}) %}
      {% else %}
        {% set action = path('app_series_restore', {seriesRate: series.seriesRateId}) %}
      {% endif %}
      <form method="post" action="{{ action }}" class="series-controls join my-4">
        <span class="btn btn-sm btn-primary cursor-default join-item">
          {% include 'icons/star.svg.twig' %}
          {{ series.score|round(2) }}
        </span>

        <input type="hidden" name="{{ csrfName }}" value="{{ csrfValue }}" />

        <button
          class="btn btn-sm btn-secondary underline join-item"
          {% if syncInProgress %}disabled{% endif %}
        >
          {% if series.state.value != 'dropped' %}Drop series{% else %}Restore series{% endif %}
        </button>
      </form>

      <table class="table">
        <thead>
        <tr>
          <th>Name</th>
          <th class="hidden md:table-cell">Kind</th>
          <th class="hidden md:table-cell">Status</th>
          <th class="hidden md:table-cell">Progress</th>
          <th>Score</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for anime in series.animes %}
          {% set animeCompleted = anime.state is not null and anime.state.value == 'completed' %}
          <tr class="{{ html_classes('series-list-item-anime', {'text-success': animeCompleted}) }}">
            <td>
              <p><a class="link" href="{{ anime.url|shikimori_url }}">{{ anime.name }}</a></p>
              <p class="md:hidden">
                {{ anime.kind ? anime.kind.value : '&mdash;' }}
                / {{ anime.status.value }}
                / {{ anime.state ? anime.state.value : '&mdash;' }}
              </p>
            </td>
            <td class="hidden md:table-cell">{{ anime.kind ? anime.kind.value : '&mdash;' }}</td>
            <td class="hidden md:table-cell">{{ anime.status.value }}</td>
            <td class="hidden md:table-cell">{{ anime.state ? anime.state.value : '&mdash;' }}</td>
            <td>{{ anime.score is not null and anime.score > 0 ? anime.score : '&mdash;' }}</td>
            <td>
              {% if anime.state is not null and anime.state.value != 'skipped' %}
                &mdash;
              {% else %}
                {% include 'components/SeriesList.anime_form.html.twig' with {
                  id: anime.id,
                  state: anime.state,
                  csrfName,
                  csrfValue,
                  syncInProgress,
                } only %}
              {% endif %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  {% else %}
    No series found.
  {% endfor %}
</section>

templates/components/SimpleForm.html.twig
<form method="post" action="{{ this.action }}" {{ attributes }}>
  <input
    type="hidden"
    name="{{ constant('App\\Controller\\Controller::COMMON_CSRF_TOKEN_FIELD') }}"
    value="{{ csrf_token(constant('App\\Controller\\Controller::COMMON_CSRF_TOKEN_ID')) }}"
  />
  <button type="submit">{% block content %}{% endblock %}</button>
</form>

templates/components/SyncStatus.html.twig
<section class="sync-status mt-4 p-4 rounded-box shadow-lg shadow-base-300 bg-base-200">
  {% if not this.user.sync.linked and this.state is null %}
    Shikimori account is not linked.
    <a href="{{ path('app_profile_link_start') }}" class="btn btn-xs btn-primary">Link your account</a> to enable sync.
  {% elseif this.state is null %}
    {% if this.sync.syncedAt is null %}
      Data was never synced.
    {% else %}
      Data synced at {{ this.sync.syncedAt|date('Y-m-d') }}.
    {% endif %}
    <twig:SimpleForm action="{{ path('app_sync_start') }}" class="btn btn-xs btn-primary">Sync</twig:SimpleForm> it now.
  {% elseif this.state == 'link_account' %}
    Linking account.
  {% elseif this.state == 'anime_rates' %}
    1/3 Syncing anime list.
  {% elseif this.state == 'series' %}
    2/3 Syncing series data.
  {% elseif this.state == 'series_rates' %}
    3/3 Syncing series states.
  {% elseif this.state == 'failed' and not this.user.sync.linked %}
    Failed to link account. Try to <a href="{{ path('app_profile_link_start') }}" class="btn btn-xs btn-primary">link
    it</a> again.
  {% elseif this.state == 'failed' %}
    Last data sync failed. Try to
    <twig:SimpleForm action="{{ path('app_sync_start') }}" class="btn btn-xs btn-primary">Sync</twig:SimpleForm>
    it again.
  {% endif %}
</section>